In [1]:
import numpy as np

In [29]:
p = 4
T = np.zeros((p, p))
T[np.tril_indices(p)] = np.ones(int(p * (p + 1) / 2))

P = np.array([
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [1, 0, 0, 0],
])

# print(P)
print(f"W:\n{P @ T @ P.T}.")

print(f"W:\n{np.rot90(P) @ T.T @ np.rot90(P)}.")

W:
[[1. 0. 0. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]].
W:
[[1. 0. 0. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]].
