In [3]:
import numpy as np 
import matplotlib.pyplot as plt
import sys
sys.path.append("..")
import helper.helper as h

In [23]:
W = np.array([[0.5, 0.3], [0.0, 0.4]])
Sigma = np.identity(2)

X = h.generate_var_2(1000, 2, W, np.identity(2))
print(np.cov(X.T))

[[1.36810112 0.28143726]
 [0.28143726 1.5033196 ]]


In [22]:
(np.linalg.inv(np.identity(4) - np.kron(W.T, W.T))) # @ np.array([1, 0, 0, 1])).reshape(2, 2)

array([[1.33333333, 0.        , 0.        , 0.        ],
       [0.25      , 1.25      , 0.        , 0.        ],
       [0.25      , 0.        , 1.25      , 0.        ],
       [0.21428571, 0.17857143, 0.17857143, 1.19047619]])

In [42]:
U = np.random.rand(2, 2)

series = np.zeros((1000, 2))

for i, x in enumerate(X):
    series[i] = X[i] @ U
    
print(np.cov(series.T))
print(U.T @ np.cov(X.T) @ U)

[[1.46931795 0.55440929]
 [0.55440929 0.58861023]]
[[1.46931795 0.55440929]
 [0.55440929 0.58861023]]
