In [1]:
import numpy as np
import itertools
from tqdm import tqdm

In [2]:
# import helper methods
import sys
sys.path.append("..")
import helper.helper as h

In [56]:
np.random.seed(seed = 12345)

## Number of dimensions, number of edges, number of samples
n, s = 10, 25

### Coefficient matrix
## First approach: A is a DAG, no model mismatch
W_true = h.generate_A(n, s, tril = False, low = 0.30, high = 0.70)

# set coefficients to be positive (else oscillating which does not make sense)
for i in range(len(W_true)):
    W_true[i][i] = np.abs(W_true[i][i])

print(f"True W:\n{np.round(W_true, 2)}.\n")

Ps = get_orderings_v2(W_true, n)

  0%|                                                                          | 983/3628800 [00:00<06:09, 9827.17it/s]

True W:
[[ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [-0.66  0.32  0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.66  0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [-0.59  0.   -0.64  0.    0.    0.    0.    0.    0.    0.  ]
 [-0.67  0.    0.45  0.    0.46  0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.63  0.    0.62  0.55  0.    0.    0.    0.  ]
 [ 0.    0.43 -0.66  0.    0.    0.69  0.63  0.    0.    0.  ]
 [ 0.    0.   -0.35  0.    0.   -0.58  0.    0.62  0.    0.  ]
 [ 0.52 -0.42  0.45  0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.54  0.62  0.    0.58  0.63  0.    0.    0.    0.  ]].



100%|██████████████████████████████████████████████████████████████████████| 3628800/3628800 [09:03<00:00, 6677.42it/s]


In [7]:
def get_orderings(W):
    
    # tracks the total number of orderings
    Ps = []
    
    perms = itertools.permutations(np.identity(np.shape(W)[0]))
    
    for perm in  tqdm(perms, total=np.math.factorial(np.shape(W)[0])):
        P = np.array(perm)
        
        if np.allclose(P.T @ W @ P, np.triu(P.T @ W @ P)):
            Ps.append(P)
            
    return Ps

In [ ]:
def get_number_of_orderings(W):
    
    # tracks the total number of orderings
    total = []
    
    perms = itertools.permutations(np.identity(np.shape(W)[0]))
    
    for perm in  tqdm(perms, total=np.math.factorial(np.shape(W)[0])):
        P = np.array(perm)
        
        if np.allclose(P.T @ W @ P, np.triu(P.T @ W @ P)):
            total += 1
            
    return total

In [55]:
def get_orderings_v2(W, n):
    
    # tracks the total number of orderings
    Ps = []
    
    perms = itertools.permutations(range(np.shape(W)[0]))
    
    for P in  tqdm(perms, total=np.math.factorial(np.shape(W)[0])):
        if np.allclose(W[:, P][P, :], np.triu(W[:, P][P, :])):
            Ps.append(P)
            
    return Ps

In [37]:
def get_number_of_orderings_v2(W, n):
    
    # tracks the total number of orderings
    total = 0
    
    perms = itertools.permutations(range(np.shape(W)[0]))
    
    for P in  tqdm(perms, total=np.math.factorial(np.shape(W)[0])):
        if np.allclose(W[:, P][P, :], np.triu(W[:, P][P, :])):
            total += 1
            
    return total

In [38]:
W = np.array([[0.5, 0.5, 0, 0.5], [0, 0.5, 0.5, 0], [0, 0, 0.5, 0], [0, 0, 0, 0.5]])
get_orderings_2(W, 4)
get_orderings(W)

100%|████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 4801.72it/s]


3

In [46]:
W = np.array([[0.5, 0.5, 0, 0, 0, 0], [0, 0.5, 0, 0.5, 0, 0], [0, 0, 0.5, 0, 0, 0], [0, 0, 0, 0.5, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]])
get_orderings(W)
get_orderings_2(W, 6)

100%|█████████████████████████████████████████████████████████████████████████████| 720/720 [00:00<00:00, 10584.14it/s]


120

In [94]:
s, n = 27, 10
total_coefs = len(np.triu_indices(n)[0])
coefs = np.append(np.ones(s), np.zeros(total_coefs - s))
np.random.shuffle(coefs)
A = np.zeros((n, n))
A[np.triu_indices(n)] = coefs
print(A)
get_orderings(A)

  0%|                                                                         | 1958/3628800 [00:00<06:10, 9785.57it/s]

[[0. 0. 1. 1. 0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


100%|██████████████████████████████████████████████████████████████████████| 3628800/3628800 [07:47<00:00, 7764.55it/s]


150

In [58]:
print(np.shape(Ps))

(1020, 10)


In [57]:
np.save("Ps_Ex", Ps)