In [58]:
import bnlearn
isachs = bnlearn.read.table("data/sachs.interventional.txt", header = TRUE, colClasses = "factor")

AttributeError: module 'bnlearn' has no attribute 'read'

In [1]:
import cdt
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
sys.path.append("..")
import helper.methods as m
import helper.helper as h

from notears.notears.notears import linear

Detecting 1 CUDA device(s).


### Get data, two kinds.

In [54]:
X_sachs, graph = cdt.data.load_dataset('sachs')
print(np.shape(X_sachs))
print(X_sachs.head())

(7466, 11)
   praf  pmek   plcg   PIP2   PIP3  p44/42  pakts473    PKA    PKC   P38  pjnk
0  26.4  13.2   8.82  18.30  58.80    6.61      17.0  414.0  17.00  44.9  40.0
1  35.9  16.5  12.30  16.80   8.13   18.60      32.5  352.0   3.37  16.5  61.5
2  59.4  44.1  14.60  10.20  13.00   14.90      32.5  403.0  11.40  31.9  19.5
3  73.0  82.8  23.10  13.50   1.29    5.83      11.8  528.0  13.70  28.6  23.1
4  33.7  19.8   5.19   9.73  24.80   21.10      46.1  305.0   4.66  25.7  81.3


In [93]:
X = np.loadtxt("../../data/real_data/sem/gene_sachs/data_sachs.txt")
X = X - np.mean(X, axis=0, keepdims=True)
# # print(np.shape(X_mod))
# print(np.round(X_mod[:5], 2))

In [99]:
# raw unmodified
X = np.loadtxt("../../data/real_data/sem/gene_sachs/data.raw.txt")
X = X - np.mean(X, axis=0, keepdims=True)
# print(np.shape(X))
print(np.round(X[:5], 1))

[[ -97.7 -132.2  -46.  -132.8   31.8  -20.   -64.2 -211.8  -13.3  -90.1
   -33.3]
 [ -88.2 -128.9  -42.6 -134.3  -18.9   -8.   -48.7 -273.8  -27.  -118.5
   -11.8]
 [ -64.7 -101.3  -40.3 -140.9  -14.   -11.7  -48.7 -222.8  -18.9 -103.1
   -53.8]
 [ -51.1  -62.6  -31.8 -137.6  -25.7  -20.8  -69.4  -97.8  -16.6 -106.4
   -50.2]
 [ -90.4 -125.6  -49.7 -141.4   -2.2   -5.5  -35.1 -320.8  -25.7 -109.3
     8. ]]


### Run experiments

In [107]:
# sachs model
W_true = np.array([
#    raf, mek, plc,pip2,pip3, erk, akt, pka, pkc, p38, jnk
    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # raf
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], # mek
    [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], # plc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], # pip2
    [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], # pip3
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], # erk
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # akt
    [1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0], # pka
    [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0], # pkc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # p38
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # jnk
])

print(np.sum(W_true != 0))
print(np.sum(W_true != 1))

20
101


In [103]:
# sachs model
W_true = np.array([
#    raf, mek, plc,pip2,pip3, erk, akt, pka, pkc, p38, jnk
    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # raf
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], # mek
    [0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], # plc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], # pip2
    [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], # pip3
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], # erk
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # akt
    [1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0], # pka
    [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0], # pkc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # p38
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # jnk
])

print(np.sum(W_true != 0))
print(np.sum(W_true != 1))

20
101


In [75]:
# sachs model, 17 edges
W_true = np.array([
#    raf, mek, plc,pip2,pip3, erk, akt, pka, pkc, p38, jnk
    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # raf
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], # mek
    [0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # plc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], # pip2
    [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # pip3
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], # erk
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # akt
    [1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0], # pka
    [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0], # pkc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # p38
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # jnk
])

print(np.sum(W_true != 0))
print(np.sum(W_true != 1))

18
103


In [76]:
# sachs expected bioligist view, 18 edges
W_true = np.array([
#    raf, mek, plc,pip2,pip3, erk, akt, pka, pkc, p38, jnk
    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # raf
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], # mek
    [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], # plc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], # pip2
    [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], # pip3
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # erk
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # akt
    [1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0], # pka
    [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0], # pkc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # p38
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # jnk
])

print(np.sum(W_true != 0))
print(np.sum(W_true != 1))

18
103


In [84]:
# sachs table, 17 edges
W_true = np.array([
#    raf, mek, plc,pip2,pip3, erk, akt, pka, pkc, p38, jnk
    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # raf
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], # mek
    [0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # plc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # pip2
    [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # pip3
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], # erk
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # akt
    [1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0], # pka
    [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0], # pkc
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # p38
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # jnk
])

print(np.sum(W_true != 0))
print(np.sum(W_true != 1))

17
104


In [138]:
def evaluate(X, W_true, W_m, method, epsilon = 0.00, verbose = True):
    # get mse
    tpr_, _, _, _, _, mse, _ = h.score(X, W_m, W_true, is_sem = True, printing = False)
    # print(mse)
    
    W = W_m.copy()
    # do thresholding to get shd
    W[np.abs(W) <= epsilon] = 0

    tpr, tnr, _, _, shd, _, _ = h.score(X, W, W_true, is_sem = True, printing = False)
    # print(shd)
    
    # do reestimated to get expected mean squared error
    # emse = expected_cost_sem(W_true, con_OLS(X, W_m != 0))
    # print(emse)
    
    if verbose:
        print(method)
        print(f"TPR: {round(tpr * 20, 3)}, TNR: {round(tnr * 101, 3)}, SHD: {shd}, Empirial Risk: {round(mse, 3)}.")
        print(np.sum(W != 0))
        
    # return results

In [89]:
def con_OLS(X, B):
    p = np.shape(B)[0]
    W = np.zeros((p, p))
    for i in range(p):
        X_F = X[:, B[:, i]]
        W[B[:, i], i] = np.linalg.inv(X_F.T @ X_F) @ X_F.T @ X[:, i]
        
    return W

In [108]:
# 4: NO TEARS, NEED TO REGULARIZE using bootstrap.
W_notears, _ = linear.notears_linear(X, lambda1 = 0.0, loss_type = "l2", w_threshold = 0.01)
print(np.round(W_notears, 1))
results = evaluate(X, W_true, W_notears, "notears")

# 4: NO TEARS, NEED TO REGULARIZE using bootstrap.
W_notears, _ = linear.notears_linear(X, lambda1 = 0.01, loss_type = "l2", w_threshold = 0.01)
print(np.round(W_notears, 1))
results = evaluate(X, W_true, W_notears, "notears")

# 4: NO TEARS, NEED TO REGULARIZE using bootstrap.
W_notears, _ = linear.notears_linear(X, lambda1 = 0.05, loss_type = "l2", w_threshold = 0.01)
print(np.round(W_notears, 1))
results = evaluate(X, W_true, W_notears, "notears")

W_notears, _ = linear.notears_linear(X, lambda1 = 0.1, loss_type = "l2", w_threshold = 0.01)
print(np.round(W_notears, 1))
results = evaluate(X, W_true, W_notears, "notears")

h: 2.0366006658889546e-07.
rho: 1e+16.
loss: (254222.62469864634, array([ 2.37713803e+06,  4.63383553e+02,  1.31569227e+05, -2.35674046e+04,
       -2.32405838e+02,  1.21181901e+04,  3.00509456e+05, -2.87421003e-02,
        2.00718205e+05,  1.77754862e+05, -1.45809356e+04,  3.55529235e+06,
        1.07467509e+05,  2.30012062e+05, -3.59012641e+04, -8.30042313e+03,
        2.01340870e+04,  5.00080514e+05,  8.38107374e+00,  3.37168972e+05,
        2.86827783e+05, -2.48612165e+04,  1.72725594e+02,  1.79111680e+01,
        9.61437268e+05,  8.31613784e+02,  2.63040920e+04,  6.83442166e+04,
        2.52438327e+05, -5.32107954e+01,  2.44993508e+05,  1.30308310e+05,
        1.24608948e+05, -6.29973872e+02, -3.19400786e+01,  1.49727809e+06,
        5.20297634e+05,  9.53113910e+04,  1.06185668e+05,  4.05435841e+05,
       -1.04488277e+01,  3.97964650e+05,  2.04135778e+05,  1.58018911e+05,
       -2.04508063e+01, -4.07778551e+00, -2.46936601e+00, -2.03827882e-01,
        8.31075129e+04, -9.8303707

notears
TPR: 9.9, TNR: 65.267, SHD: 46, Empirial Risk: 499924.535.
h: 1.8047024141765178e-07.
rho: 1e+16.
loss: (253231.05548214717, array([ 2.24409162e+06,  6.36452418e+01,  1.08082557e+05, -2.24679187e+04,
       -3.99352205e+03,  1.57127613e+04,  2.71870251e+05, -1.83423414e+01,
        1.85625449e+05,  1.64748497e+05, -2.47917134e+04,  3.30708258e+06,
        1.12593588e+05,  1.90352851e+05, -3.49770372e+04, -1.09785011e+04,
        3.56833421e+04,  4.40951775e+05, -4.95808764e+01,  3.21986694e+05,
        2.69773863e+05, -2.81425726e+04,  1.33428425e+02,  2.99206149e+01,
        9.05443478e+05,  1.04080564e+02,  2.76713205e+04,  5.32274488e+04,
        2.28271225e+05, -2.41951636e+01,  2.23897764e+05,  1.27655209e+05,
        9.76542729e+04, -2.71540444e+02,  2.79973571e+01,  1.41351247e+06,
        4.98430064e+05,  1.04474387e+05,  8.62317804e+04,  3.70357934e+05,
        5.40072023e+01,  3.80077739e+05,  1.93309728e+05,  1.41199028e+05,
        1.96877599e+01,  2.88624887e+00,  

notears
TPR: 9.9, TNR: 63.228, SHD: 48, Empirial Risk: 499878.007.


In [125]:
# 4: NO TEARS, NEED TO REGULARIZE using bootstrap.
W_notears_0, _ = linear.notears_linear(X, lambda1 = 0.0, loss_type = "l2", w_threshold = 0.1)
print(np.round(W_notears, 1))
results = evaluate(X, W_true, W_notears, "notears")

# 4: NO TEARS, NEED TO REGULARIZE using bootstrap.
W_notears_05, _ = linear.notears_linear(X, lambda1 = 0.04, loss_type = "l2", w_threshold = 0.1)
print(np.round(W_notears, 1))
results = evaluate(X, W_true, W_notears, "notears")

# 4: NO TEARS, NEED TO REGULARIZE using bootstrap.
W_notears_10, _ = linear.notears_linear(X, lambda1 = 0.15, loss_type = "l2", w_threshold = 0.1)
print(np.round(W_notears, 1))
results = evaluate(X, W_true, W_notears, "notears")

W_notears_25, _ = linear.notears_linear(X, lambda1 = 0.25, loss_type = "l2", w_threshold = 0.1)
print(np.round(W_notears, 1))
results = evaluate(X, W_true, W_notears, "notears")

h: 2.0366006658889546e-07.
rho: 1e+16.
loss: (254222.62469864634, array([ 2.37713803e+06,  4.63383553e+02,  1.31569227e+05, -2.35674046e+04,
       -2.32405838e+02,  1.21181901e+04,  3.00509456e+05, -2.87421003e-02,
        2.00718205e+05,  1.77754862e+05, -1.45809356e+04,  3.55529235e+06,
        1.07467509e+05,  2.30012062e+05, -3.59012641e+04, -8.30042313e+03,
        2.01340870e+04,  5.00080514e+05,  8.38107374e+00,  3.37168972e+05,
        2.86827783e+05, -2.48612165e+04,  1.72725594e+02,  1.79111680e+01,
        9.61437268e+05,  8.31613784e+02,  2.63040920e+04,  6.83442166e+04,
        2.52438327e+05, -5.32107954e+01,  2.44993508e+05,  1.30308310e+05,
        1.24608948e+05, -6.29973872e+02, -3.19400786e+01,  1.49727809e+06,
        5.20297634e+05,  9.53113910e+04,  1.06185668e+05,  4.05435841e+05,
       -1.04488277e+01,  3.97964650e+05,  2.04135778e+05,  1.58018911e+05,
       -2.04508063e+01, -4.07778551e+00, -2.46936601e+00, -2.03827882e-01,
        8.31075129e+04, -9.8303707

notears
TPR: 7.0, TNR: 84.693, SHD: 20, Empirial Risk: 583913.436.
14
h: 1.802552915819433e-07.
rho: 1e+16.
loss: (253231.0399690463, array([ 2.22995025e+06,  3.06949649e+02,  1.21205715e+05, -2.86384987e+04,
       -4.77865739e+03,  1.11725858e+04,  2.82768799e+05, -2.16012137e+00,
        1.93367337e+05,  1.66375356e+05, -2.86054316e+04,  3.30444445e+06,
        9.80296286e+04,  1.98611541e+05, -3.63435557e+04, -1.37424445e+04,
        1.68140161e+04,  4.42948154e+05, -1.44764817e+01,  3.31837561e+05,
        2.63754236e+05, -2.92841101e+04,  1.49063575e+02,  4.77808585e+00,
        8.96767909e+05,  2.23258249e+02,  4.61362117e+04,  5.23198325e+04,
        2.20440852e+05, -5.47730839e+01,  2.26794535e+05,  1.25969333e+05,
        9.76467971e+04, -3.27276922e+02, -3.21504825e+01,  1.40786523e+06,
        4.87965711e+05,  1.02848199e+05,  8.59397227e+04,  3.53777620e+05,
        2.44075697e+00,  3.81370159e+05,  1.95997146e+05,  1.43283091e+05,
        8.54996708e+00, -2.18272760e+00, 

notears
TPR: 7.0, TNR: 84.693, SHD: 20, Empirial Risk: 583913.436.
14


In [147]:
results = evaluate(X, W_true, W_notears_0, "notears", epsilon = 0.437)
results = evaluate(X, W_true, W_notears_05, "notears", epsilon = 0.437)
results = evaluate(X, W_true, W_notears_10, "notears", epsilon = 0.5)
results = evaluate(X, W_true, W_notears_25, "notears", epsilon = 0.437)

notears
TPR: 8.0, TNR: 93.0, SHD: 20, Empirial Risk: 502436.663.
16
notears
TPR: 8.0, TNR: 92.0, SHD: 21, Empirial Risk: 504543.088.
17
notears
TPR: 7.0, TNR: 94.0, SHD: 20, Empirial Risk: 504372.553.
14
notears
TPR: 8.0, TNR: 92.0, SHD: 21, Empirial Risk: 502619.758.
17


In [140]:
m.T, m.p = np.shape(X)
T, p = np.shape(X)
iters = 1000

# do MCMC_g
W_rw_2 = m.rw_2(X, X, np.identity(p), iters, is_sem = True)[1]
print(np.round(W_rw_2, 1))
# print(np.sum(np.abs(W_rw_2) >= 0.2))
results = evaluate(X, W_true, W_rw_2, "rw_2", epsilon = 0.437)
    
# 3.1: MCMC 1
W_mcmc_1 = m.mcmc_1(X, X, iters, np.identity(p), is_sem = True)[1]
print(np.round(W_mcmc_1, 1))
results = evaluate(X, W_true, W_mcmc_1, "mcmc_r", epsilon = 0.437)

# 3.4: MCMC Greedy
W_mcmc_4 = m.mcmc_4(X, X, iters, np.identity(p), is_sem = True)[1]
print(np.round(W_mcmc_4, 1))
results = evaluate(X, W_true, W_mcmc_4, "mcmc_g", epsilon = 0.437)
    
# 4: NO TEARS, NEED TO REGULARIZE using bootstrap.
# W_notears, _ = linear.notears_linear(X, lambda1 = 0.0, loss_type = "l2", w_threshold = 0.01)
# print(np.round(W_notears, 1))
# results = evaluate(X, W_true, W_notears, "notears")

# 6: DAG-OMP, NEED TO REGULARIZE using cross-validation.
W_omp, _ = m._K_OMP(X, X, F = [], normalize = True, is_sem = True)
print(np.round(W_omp, 1))
results = evaluate(X, W_true, W_omp, "dagomp", epsilon = 0.437)

# 7: DAG-LASSO, NEED TO REGULARIZE using bootstrap.
W_ols_dag = con_OLS(X, B_V_LINGNAM_OLS_Q_SEM(X) != 0)
print(np.round(W_ols_dag, 1))
results = evaluate(X, W_true, W_ols_dag, "dagols", epsilon = 0.437)

100%|█████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:03<00:00, 279.80it/s]


[[ 0.   1.5  0.   0.   0.   0.   0.  -0.2  0.   0.  -0.1]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.1]
 [ 0.2  0.   0.   1.6 -0.1  0.   0.  -0.5  0.1  0.1  0.1]
 [-0.1 -0.   0.   0.   0.1  0.   0.  -0.   0.  -0.  -0. ]
 [ 0.  -0.1  0.   0.   0.   0.   0.   0.3  0.  -0.  -0.1]
 [-1.4 -0.2 -1.1  0.   0.   0.   2.1  4.9 -0.4 -0.3 -0.3]
 [ 0.7  0.1  0.8 -0.  -0.   0.   0.  -0.6  0.3  0.2  0.3]
 [ 0.  -0.   0.   0.   0.   0.   0.   0.   0.   0.  -0. ]
 [ 0.1 -0.   0.   0.  -0.   0.   0.   1.   0.   5.   1.4]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.3  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]]


  2%|█▉                                                                             | 24/1000 [00:00<00:04, 233.01it/s]

rw_2
TPR: 6.0, TNR: 94.0, SHD: 21, Empirial Risk: 503721.255.
13


100%|█████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:04<00:00, 236.97it/s]


[[ 0.   1.5  0.  -0.   0.   0.   0.   0.7  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.6  0.   0.   0. ]
 [ 0.1  0.   0.   1.6  0.   0.   0.2 -0.4  0.2  0.1  0.2]
 [ 0.  -0.   0.   0.   0.   0.   0.  -0.   0.   0.   0. ]
 [-0.  -0.1  0.4  0.8  0.   0.  -0.1  0.2 -0.1 -0.  -0.1]
 [-1.4 -0.2  0.6 -0.  -0.   0.   1.8  4.7  0.2 -0.3  0.2]
 [ 0.7  0.1  0.   0.   0.   0.   0.  -0.5  0.   0.2  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [-0.3 -0.   0.   0.1  0.   0.   0.1  1.4  0.   4.9  1.8]
 [ 0.1  0.   0.  -0.   0.   0.   0.  -0.3  0.   0.   0. ]
 [-0.1  0.   0.  -0.   0.   0.   0.1 -0.2  0.   0.1  0. ]]


  3%|██▏                                                                            | 27/1000 [00:00<00:03, 262.22it/s]

mcmc_r
TPR: 7.0, TNR: 93.0, SHD: 21, Empirial Risk: 505109.172.
15


100%|█████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:03<00:00, 253.94it/s]


[[ 0.   1.5 -0.4  0.   0.   0.   0.   0.7  0.  -0.1 -0.1]
 [ 0.   0.   0.3 -0.   0.   0.   0.  -0.6  0.   0.1  0.1]
 [ 0.   0.   0.   1.6  0.   0.   0.  -0.4  0.   0.1  0.1]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.   0.  -0.  -0. ]
 [ 0.  -0.   0.5  0.8  0.  -0.  -0.1  0.2 -0.1  0.  -0.1]
 [-1.6 -0.3 -0.8 -0.   0.   0.   1.9  4.7  0.3 -0.2 -0.4]
 [ 0.8  0.2  0.6  0.   0.   0.   0.  -0.5  0.   0.1  0.3]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.2  0.   0.3  0.1  0.   0.   0.4  1.4  0.   4.8  1.7]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.3  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.2  0.   0.1  0. ]]
mcmc_g
TPR: 8.0, TNR: 92.0, SHD: 21, Empirial Risk: 499861.538.
17
[[ 0.   1.5  0.   0.   0.   0.   0.   0.7  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.6  0.   0.   0. ]
 [ 0.2  0.   0.   1.6  0.   0.   0.  -0.4  0.   0.1  0. ]
 [-0.1 -0.   0.   0.   0.   0.   0.  -0.   0.  -0.   0. ]
 [ 0.  -0.1  0.5  0.8  0.  -0.  -0.   0.2 -0.1  0.  -0.1]
 [-1

### Compare to ground truth

In [72]:
print(W_notears)

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.         -0.27373133  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.42543617
   0.          0.          0.          0.          0.        ]
 [ 0.75849663  0.          0.          0.          0.          0.
   0.          0.      

In [9]:
import statsmodels.api as sm
import scipy.linalg as slin

def _h(W):
    """Evaluate value and gradient of acyclicity constraint."""
    W2 = W.copy()
    E = slin.expm(W2)  # (Zheng et al. 2018)
    h = np.trace(E) - p

    return h

def in_cycle(W, i, j, epsilon = 1e-32):
    
    h_val = _h(W)
    
    w_tmp = W[i][j]
    W[i][j] = 0
    h_new = _h(W)
    W[i][j] = w_tmp
    
    return np.abs(h_val - h_new) > epsilon

def B_V_LINGNAM_OLS_Q_SEM(X):
    """OLS solution W, data X"""
    
    T, p = np.shape(X)
    
    # get full OLS solution of W
    B = np.ones((p, p)) - np.identity(p)
    # print(B)
    W = con_OLS(X, B != 0)
    
    # non_violators
    violators = np.ones((p, p))
    
    # while we still do not have a DAG
    while not h.is_dag(W):     
        if np.sum(W != 0) % 50 == 0: print(np.sum(W != 0))
        # print(h.is_dag(W))
        
        # find edge with smallest coefficient which might be a violator
        i_list, j_list = np.where((np.abs(W) == np.min(np.abs(W[(W * violators).nonzero()]))))
        i, j = i_list[0], j_list[0]
        
        # if it is contained in a cycle, remove it
        # if not, never consider it again
        if in_cycle(W, i, j):
            W[i][j] = 0
            violators[i][j] = 0
        
            # update column
            idx = np.nonzero(W[:, j])[0]
            W[idx, j] = (np.linalg.inv(X[:, idx].T @ X[:, idx]) @ X[:, idx].T @ X[:, j])
        else:
            violators[i][j] = 0
  
    # return the DAG W
    return W