# Investigating the $h(W)$ function

In [68]:
import numpy as np
import scipy.linalg as slin

In [69]:
n = 3

In [71]:
def h(W):
    """Evaluate value and gradient of acyclicity constraint, ALLOW self-loops."""
    
    V = W * W-np.diag(np.diag(W * W))
    E = slin.expm(V)  
    h = np.trace(E) - np.shape(W)[0] 
    
    G_h = E.T * V * 2 
    return h, G_h

def h_2(W):
    """Evaluate value and gradient of acyclicity constraint."""
    
    V = W * W
    E = slin.expm(V)  
    h = np.trace(E) - np.shape(W)[0] 
    
    G_h = E.T * V * 2
    return h, G_h

In [72]:
W = np.zeros((n, n))
print(W)
print(h(W)[0], ",", h_2(W)[0])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0.0 , 0.0


In [73]:
W = np.ones((n, n))
print(W)
print(h(W)[0], ",", h_2(W)[0])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
5.124814981273538 , 19.085536923187686


In [74]:
W = np.zeros((n, n))
W[np.tril_indices(n)] = 1
print(W)
print(h(W)[0], ",", h_2(W)[0])

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
0.0 , 5.154845485377136


In [76]:
W = np.array([[0.04477571, -0.59422257, -0.92507845],
              [-0.35883158, -0.97753726, -1.04441649],
              [-0.74285576,  0.05889454, -0.12959465]])
print(h(W)[0], ",", h_2(W)[0])

0.6559190822780434 , 2.3603367618537234


In [79]:
def _h(W):
    """Evaluate value and gradient of acyclicity constraint."""

    V = W * W - np.diag(np.diag(W * W))
    E = slin.expm(V)  # (Zheng et al. 2018)
    h = np.trace(E) - np.shape(W)[0] 

    G_h = E.T * V * 2#-2*np.diag(np.diag(W))
    
    return h, G_h

print(_h(W)[0])

0.6559190822780434
