In [5]:
import numpy as np
import scipy.linalg as sci
import numpy as np
from numpy import linalg as lg

Assumption: We can write any permutation matrix $$P = \prod_{i,j: i < j} P_{ij}^{\alpha_{ij}}$$ for $\alpha_{ij} \in \{0, 1\}$. Here $P_{ij}$ is the transposition matrix that permutes row $i$ and $j$. We know that we can write any permutation matrix as a composition of transposition matrices, but note that the product above has a fixed order.

An easy way to verify that each permutation matrix can be decomposed using at most $n - 1$ non-zero $\alpha_{ij}$, we consider a $\textit{selection sort}$ approach. Let $j$ be the row where the first entry is a 1. We swap row $i = 1$ and row $j$. Then, let $j$ be the row where the second entry is a 1 ($j > 1>$). We swap row $i = 2$ and row $j$. We do this $n - 1$ times after which the first $n - 1$ entries are correct, and since we have $n$ entries in total, all $n$ entries are correct.

If that is indeed true we have a valid representation of all permutation matrices, parametrized through the ${n \choose 2}$
parameters $\mathbf{α}$. This we can relax now by letting $\alpha \in \mathbb{R}^{n \choose 2}$, where we define the diagonal decomposition of $P_{ij}^{\alpha_{ij}}$ as $$P_{ij}^{\alpha_{ij}} = U^TD^{\alpha_{ij}}U.$$
We know that $D = \text{diag}(−1, 1, 1, ....)$, so $D^{\alpha_{ij}} = \text{diag}(c, 1, 1...)$, where $c$ is a complex number. 

This representation will avoid having problems with the inverse, as $$\left(P = \prod_{i,j: i < j} P_{ij}^{\alpha_{ij}}\right)^{-1} = \prod_{i,j: i < j} \left(P_{ij}^{\alpha_{ij}}\right)^{-1}.$$
Now, for $\alpha_{ij} \in \{0, 1\}$, the inverse is simply
$$\left(P_{ij}^{\alpha_{ij}}\right)^{-1} = \left(P_{ij}^{\alpha_{ij}}\right)^T = P_{ij}^{\alpha_{ij}},$$
which in fact is swapping $\textit{column}$ $i$ and $j$, rather than row $i$ and $j$.
Now, for $\alpha_{ij} \in \mathbb{R}$, the inverse is slightly more involved, but still doable.
$$A^\beta = e^{\beta \ln(A)} = \sum_{k=0}^\infty\frac{1}{k!}\left(\beta \ln(A)\right)^k.$$

In [ ]:
# get the two rows to swap
i, j = np.random.choice(n, 2, replace = False)

# swap row i and row j
P[[i, j]] = P[[j, i]]

### Decompositions
#### Eigendecomposition
Since we know that we only permute two rows, we know that the eigenvalues are $\lambda_1 = -1, \lambda_i = 1, i = 1, \cdots, n.$ Hence, the eigendecomposition is 
$$P^{\alpha_{ij}}_{ij} = U^T \Lambda U,$$
where $$\Lambda = \text{diag}\left(-1, 1, \ldots, 1\right).$$

In [10]:
evls, evcs = lg.eig(P_pow)
print(np.round(evls, 2))
print(evcs)

Lambda = np.diag(evls)
print(evcs @ Lambda @ lg.inv(evcs))

print(evcs @ Lambda @ evcs.T)

[ 1.  -0.j   -0.71-0.71j  1.  +0.j  ]
[[-0.        +0.00000000e+00j  0.        +0.00000000e+00j
   1.        +0.00000000e+00j]
 [ 0.70710678-2.77555756e-17j -0.70710678-8.32667268e-17j
   0.        +0.00000000e+00j]
 [ 0.70710678+0.00000000e+00j  0.70710678+0.00000000e+00j
   0.        +0.00000000e+00j]]
[[1.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.14644661-0.35355339j 0.85355339+0.35355339j]
 [0.        +0.j         0.85355339+0.35355339j 0.14644661-0.35355339j]]
[[1.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.14644661-0.35355339j 0.85355339+0.35355339j]
 [0.        +0.j         0.85355339+0.35355339j 0.14644661-0.35355339j]]


In [7]:
P = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
P_pow = sci.fractional_matrix_power(P, 1.25)
print(P_pow)

lu, d, perm = sci.ldl(P, lower = 0)
print("LU:\n", lu[perm, :])
print("D:\n", d)
print("perm:\n", perm)

[[1.        +0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.14644661-0.35355339j 0.85355339+0.35355339j]
 [0.        +0.j         0.85355339+0.35355339j 0.14644661-0.35355339j]]
LU:
 [[ 1. -0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
D:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
perm:
 [0 1 2]


In [8]:



power = 1.0
print(P)

P_power = sci.fractional_matrix_power(P, power)
print(P_power)

P_inv = sci.inv(P_power)
print(P_inv)

print(np.round(P_power @ P_inv, 5))

[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[ 1. -0. -0.]
 [ 0. -0.  1.]
 [ 0.  1.  0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
D = np.diag((-1, 1, 1))
print(D)
print(sci.fractional_matrix_power(D, 1.75))

[[-1  0  0]
 [ 0  1  0]
 [ 0  0  1]]
[[0.70710678-0.70710678j 0.        +0.j         0.        +0.j        ]
 [0.        +0.j         1.        +0.j         0.        +0.j        ]
 [0.        +0.j         0.        +0.j         1.        +0.j        ]]


In [144]:
-1 ** 1.25

-1.0