In [ ]:
import sys
!{sys.executable} -m pip install cdt

In [ ]:
import cdt

In [ ]:
#Import libraries
import cdt
from cdt import SETTINGS
SETTINGS.verbose=False
SETTINGS.NJOBS=16
SETTINGS.rpath = "D:\Programma's\R-4.1.1\bin\R"
import networkx as nx
import time
# A warning on R libraries might occur. It is for the use of the r libraries that could be imported into the framework
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
# Load data and graph solution
data, solution = cdt.data.load_dataset('sachs')
nx.draw_networkx(solution, font_size=8) # The plot function allows for quick visualization of the graph. 
plt.show()
data.head()

In [ ]:
import networkx as nx
from cdt.causality.graph import GES
from cdt.data import load_dataset

data, graph = load_dataset("sachs")
obj = GES()
# The predict() method works without a graph, or with a
# directed or udirected graph provided as an input
output = obj.predict(data)    #No graph provided as an argument

output = obj.predict(data, nx.Graph(graph))  # With an undirected graph
output = obj.predict(data, graph)  # With a directed graph

# To view the graph created, run the below commands:
nx.draw_networkx(output, font_size=8)
plt.show()

In [ ]:
generator = cdt.data.AcyclicGraphGenerator('gp_add', noise_coeff=.2, nodes=10, parents_max=3)
data, graph = generator.generate()
data.head()

In [ ]:
sam = cdt.causality.graph.SAM(nruns=1)
prediction = sam.predict(data)

In [ ]:
from cdt.metrics import (precision_recall, SHD)
[metric(graph, prediction) for metric in (precision_recall, SHD)]

In [4]:
import cdt
import networkx as nx
data, graph = cdt.data.load_dataset('sachs')
print(data.head())

glasso = cdt.independence.graph.Glasso()
skeleton = glasso.predict(data)
print(nx.adjacency_matrix(skeleton).todense())

   praf  pmek   plcg   PIP2   PIP3  p44/42  pakts473    PKA    PKC   P38  pjnk
0  26.4  13.2   8.82  18.30  58.80    6.61      17.0  414.0  17.00  44.9  40.0
1  35.9  16.5  12.30  16.80   8.13   18.60      32.5  352.0   3.37  16.5  61.5
2  59.4  44.1  14.60  10.20  13.00   14.90      32.5  403.0  11.40  31.9  19.5
3  73.0  82.8  23.10  13.50   1.29    5.83      11.8  528.0  13.70  28.6  23.1
4  33.7  19.8   5.19   9.73  24.80   21.10      46.1  305.0   4.66  25.7  81.3
[[ 9.26744031e-04 -6.13751618e-04  1.66612981e-05 -1.10912131e-06
  -3.04172363e-05 -9.71526466e-05  7.00340545e-05 -1.93863471e-06
  -7.31774543e-06  2.29788237e-06  8.31264711e-06]
 [-6.13751618e-04  4.14978956e-04 -1.37962487e-05  1.42164753e-06
   2.04443539e-05  8.24208108e-05 -5.63238668e-05  1.62688021e-06
   8.63444133e-06 -2.88779755e-06 -4.69605195e-06]
 [ 1.66612981e-05 -1.37962487e-05  2.60824802e-04 -1.35895911e-04
   8.78979413e-05  2.17234579e-05 -2.07856535e-05  1.23313600e-06
   2.12954874e-05 -3.2286924

In [5]:
new_skeleton = cdt.utils.graph.remove_indirect_links(skeleton, alg='aracne')
print(nx.adjacency_matrix(new_skeleton).todense())

[[9.26744031e-04 0.00000000e+00 1.66612981e-05 0.00000000e+00
  0.00000000e+00 0.00000000e+00 7.00340545e-05 0.00000000e+00
  0.00000000e+00 2.29788237e-06 8.31264711e-06]
 [0.00000000e+00 4.14978956e-04 0.00000000e+00 0.00000000e+00
  2.04443539e-05 8.24208108e-05 0.00000000e+00 1.62688021e-06
  8.63444133e-06 0.00000000e+00 0.00000000e+00]
 [1.66612981e-05 0.00000000e+00 2.60824802e-04 0.00000000e+00
  8.78979413e-05 2.17234579e-05 0.00000000e+00 1.23313600e-06
  2.12954874e-05 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 8.68622146e-05
  0.00000000e+00 3.08709259e-06 0.00000000e+00 9.09261370e-09
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.04443539e-05 8.78979413e-05 0.00000000e+00
  6.09681818e-04 0.00000000e+00 1.78188074e-05 0.00000000e+00
  0.00000000e+00 0.00000000e+00 5.79322379e-06]
 [0.00000000e+00 8.24208108e-05 2.17234579e-05 3.08709259e-06
  0.00000000e+00 1.10860610e-03 0.00000000e+00 0.00000000e+00
  0.00000000e+00

In [6]:
model = cdt.causality.graph.GES()
output_graph = model.predict(data, new_skeleton)
print(nx.adjacency_matrix(output_graph).todense())

GES is ran on the skeleton of the given graph.


[[0 0 0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 1 0 0 1 1]
 [0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [7]:
from cdt.metrics import (precision_recall, SID, SHD)
scores = [metric(graph, output_graph) for metric in (precision_recall, SID, SHD)]
print(scores)

[(0.46354453627180897, [(0.1487603305785124, 1.0), (0.4, 0.4444444444444444), (1.0, 0.0)]), array(64.), 22]
