In [31]:
import pycausal
import pandas as pd
import sys
import pydot

from pycausal.pycausal import pycausal as pc
from pycausal import search as s

import sys
sys.path.append("..")
from notears.notears.notears import utils

from IPython.display import SVG

import numpy as np

In [33]:
import cdt
import networkx as nx
import pandas as pd

data, graph = cdt.data.load_dataset('sachs')
B_true_2 = np.array(nx.adjacency_matrix(graph).todense())

In [76]:
data_dir = "https://raw.githubusercontent.com/bd2kccd/py-causal/master/data/charity.txt"
df = pd.read_table(data_dir, sep="\t")

In [3]:
pc = pc()
pc.start_vm()

In [4]:
tetrad = s.tetradrunner()

In [5]:
tetrad.listScores()

bdeu-score
cci-score
cg-bic-score
cg-other-bic-score
d-sep-score
degen-gauss-bic
disc-bic-score
disc-mixed-bic-score
mnlr-bic-score
mvp-bic-score
sem-bic


In [12]:
# tetrad.getAlgorithmParameters(algoId = 'fges', scoreId = 'sem-bic')

faithfulnessAssumed: This is a parameter for FGES (“Fast GES”). If this is set to ‘Yes’, it will be assumed that if X _||_ Y, by an independence test, then X _||_ Y | Z for nonempty Z. If the model is faithful to the data, this will necessarily be the case. However, there are some non-faithful examples one can propose where this is not the case. If one is worried about this kind of unfaithfulness, one should set this parameter to ‘No’. If one is willing to tolerate this kind of unfaithfulness, then setting this parameter to ‘Yes’ leads to significantly faster searches. (java.lang.Boolean) [default:true]
symmetricFirstStep: For discrete searches, and in some other situations, it may make a difference for an edge X—Y whether you score X->Y or X<-Y, even though theoretically they should have the same score. If this parameter is set to “Yes”, both scores will be calculated and the higher score used. (Recall we are calculating BIC as 2L – c k ln N, where c is the penalty discount.) (java.la

In [18]:
tetrad.run(algoId = 'fges', dfs = data, maxDegree = -1, faithfulnessAssumed = True, verbose = True)

In [24]:
dot_str = pc.tetradGraphToDot(tetrad.getTetradGraph())
graphs = pydot.graph_from_dot_data(dot_str)
svg_str = graphs[0].create_svg()
SVG(svg_str)
G_GES = nx.drawing.nx_pydot.from_pydot(graphs[0])

In [34]:
B_GES = nx.adjacency_matrix(G_GES).todense()
utils.count_accuracy(B_true_2, B_GES)

{'fdr': 0.7428571428571429,
 'tpr': 0.5,
 'fpr': 0.7027027027027027,
 'shd': 33,
 'nnz': 35}

In [12]:
import cdt
import networkx as nx

In [13]:
model = cdt.causality.graph.GES()
output_graph = model.predict(df)
print(nx.adjacency_matrix(output_graph).todense())

[[0 0 1 0 0]
 [0 0 0 0 1]
 [1 0 0 0 1]
 [0 0 0 0 1]
 [0 1 1 1 0]]


In [23]:
import sys
sys.path.append("..")

from notears.notears.notears import utils
from notears.notears.notears import linear

import numpy as np

h: 1.2131646798252405e-09.
rho: 100000000000.0.
loss: (2.517075144088772, array([ 0.01994018,  0.08731709,  0.00906624, -0.03357818,  0.04984135,
       -0.00170171,  0.02012402, -0.00024068, -0.01153043, -0.00020637,
       -0.00139497,  0.02209305,  0.01974629, -0.00042375,  0.02764053,
        0.00078235,  0.00207607, -0.00198867,  0.02174754, -0.00064124,
       -0.00275653,  0.01746351, -0.00523709, -0.03180316,  0.02020474,
       -0.01994018, -0.08731709, -0.00906624,  0.03357818, -0.04984135,
        0.00170171, -0.02012402,  0.00024068,  0.01153043,  0.00020637,
        0.00139497, -0.02209305, -0.01974629,  0.00042375, -0.02764053,
       -0.00078235, -0.00207607,  0.00198867, -0.02174754,  0.00064124,
        0.00275653, -0.01746351,  0.00523709,  0.03180316, -0.02020474])).
[[ 0.   0.   0.   0.   0. ]
 [ 1.8  0.  -1.1  0.   1.3]
 [ 0.9  0.   0.   0.   0. ]
 [ 1.5 -0.6  1.8  0.  -0.8]
 [ 1.3  0.   1.5  0.   0. ]]


In [39]:
# graph = nx.from_numpy_matrix()
scores = [SHD(B_true, output_graph)]
print(scores)

[4.0]


In [41]:
model = cdt.causality.graph.GES()
output_graph = model.predict(pd.DataFrame(X))
print(nx.adjacency_matrix(output_graph).todense())

from cdt.metrics import SHD
print(B_true)
scores = [SHD(B_true, output_graph)]
print(scores)

[[0 0 0 0 0]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 0 1 0 0]
 [1 0 0 0 0]]
[[0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 1. 0.]]
[4.0]


In [17]:
tetrad = s.tetradrunner()
tetrad.run(algoId = 'ges', dfs = data, maxDegree = -1, faithfulnessAssumed = True, verbose = True)

KeyError: 'ges'

In [16]:
dot_str = pc.tetradGraphToDot(tetrad.getTetradGraph())
graphs = pydot.graph_from_dot_data(dot_str)
svg_str = graphs[0].create_svg()
SVG(svg_str)

JavaException: <Java object at 0x8691440>

In [44]:
p, num_edges = 5, 10

# generate X, Psi
B_true = utils.simulate_dag(p, num_edges, 'ER')
W_true = utils.simulate_parameter(B_true)
X = utils.simulate_linear_sem(W_true, 1000, 'gauss')

In [47]:
W_NT, h_val = linear.notears_linear(X, lambda1 = 0.0, loss_type = 'l2', verbose = False)
print(np.round(W_NT, 1))

[[ 0.   0.   0.   0.   0. ]
 [-0.4  0.   0.   0.   0. ]
 [ 1.   0.   0.   0.   0. ]
 [ 0.  -2.3 -0.9  0.   1.6]
 [ 0.4 -1.5  0.8  0.   0. ]]


In [49]:
model = cdt.causality.graph.GES()
output_graph = model.predict(pd.DataFrame(X))
print(nx.adjacency_matrix(output_graph).todense())

[[0 1 1 0 1]
 [1 0 1 1 1]
 [1 1 0 1 1]
 [0 1 1 0 0]
 [1 1 1 0 0]]


In [51]:
tetrad = s.tetradrunner()
tetrad.run(algoId = 'fges', dfs = pd.DataFrame(X), maxDegree = -1, faithfulnessAssumed = True, verbose = True)

In [74]:
dot_str = pc.tetradGraphToDot(tetrad.getTetradGraph())
graphs = pydot.graph_from_dot_data(dot_str)

print(graphs[0].get_edges())

[<pydot.Edge object at 0x00000211E532AE80>, <pydot.Edge object at 0x00000211E4EA3AC8>, <pydot.Edge object at 0x00000211E5027CC0>, <pydot.Edge object at 0x00000211E5027F98>, <pydot.Edge object at 0x00000211E5034630>, <pydot.Edge object at 0x00000211E5035C88>, <pydot.Edge object at 0x00000211E4E71320>, <pydot.Edge object at 0x00000211E4E77CF8>]
