In [19]:
import numpy as np

In [23]:
epsilon = 0.05
P = np.ones((3, 3)) / 3

P[0][0] -= epsilon
P[1][1] -= epsilon
P[0][1] += epsilon
P[1][0] += epsilon

print(f"P:\n{P}\n")
print(f"Inv(P):\n{np.linalg.inv(P)}")

P:
[[0.28333333 0.38333333 0.33333333]
 [0.38333333 0.28333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]

Inv(P):
[[ 4.50359963e+15  4.50359963e+15 -9.00719925e+15]
 [ 4.50359963e+15  4.50359963e+15 -9.00719925e+15]
 [-9.00719925e+15 -9.00719925e+15  1.80143985e+16]]
